#!/usr/bin/env node
/**
 * Audit streak.
 *
 * Runs the full audit repeatedly and only succeeds on N *consecutive* clean passes.
 * A single failing run resets the streak to zero, because the point is stability:
 * an audit that passes nine times out of ten is telling you something is racy.
 *
 *   node scripts/audit-streak.mjs          run until 10 consecutive passes
 *   node scripts/audit-streak.mjs 25       run until 25
 *   node scripts/audit-streak.mjs 10 40    10 consecutive, give up after 40 attempts
 *
 * Writes AUDIT-STREAK.md with one row per attempt.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = Number(process.argv[2] ?? 10);
const maxAttempts = Number(process.argv[3] ?? target * 4);

const PORT = 4321;

/** The audit boots a server on a fixed port; a leftover one would poison every run. */
const portFree = async () => {
  const net = await import("node:net");
  return new Promise((resolve) => {
    const socket = net.connect(PORT, "127.0.0.1");
    socket.setTimeout(500);
    socket.once("connect", () => {
      socket.destroy();
      resolve(false);
    });
    socket.once("error", () => resolve(true));
    socket.once("timeout", () => {
      socket.destroy();
      resolve(true);
    });
  });
};

if (!(await portFree())) {
  console.error(`\x1b[31mPort ${PORT} is busy. Stop whatever holds it before running a streak.\x1b[0m`);
  process.exit(1);
}

const attempts = [];
let streak = 0;
let best = 0;

for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
  const startedAt = Date.now();
  const run = spawnSync("node", ["scripts/audit.mjs", "--quiet"], {
    cwd: root,
    encoding: "utf-8",
    timeout: 900_000,
  });
  const seconds = ((Date.now() - startedAt) / 1000).toFixed(1);
  const out = (run.stdout ?? "") + (run.stderr ?? "");
  const summary =
    out.match(/(\d+)\/(\d+) checks pass/)?.[0] ??
    (run.status === 0 ? "passed (no summary line)" : `exit ${run.status}`);
  const failures = [...out.matchAll(/^\s*(\d+)\s+\x1b\[31mFAIL\x1b\[0m\s+(.+)$/gm)].map(
    (m) => `#${m[1]} ${m[2]}`,
  );

  const clean = run.status === 0 && failures.length === 0;
  streak = clean ? streak + 1 : 0;
  best = Math.max(best, streak);
  attempts.push({ attempt, clean, seconds, summary, failures, streak });

  const mark = clean ? "\x1b[32mPASS\x1b[0m" : "\x1b[31mFAIL\x1b[0m";
  console.log(
    `attempt ${String(attempt).padStart(2)}  ${mark}  ${seconds.padStart(5)}s  ${summary}` +
      `  streak ${streak}/${target}` +
      (failures.length ? `\n            ${failures.join("\n            ")}` : ""),
  );

  if (streak >= target) break;
  if (!clean && attempt >= maxAttempts) break;
}
const streakMet = streak >= target;

/**
 * The report this script writes is itself a file in the tree, and the audit checks the
 * tree. Writing it and then declaring success would let the harness pass while leaving
 * the repository in a state that fails the very next audit — which is exactly what the
 * first version of this script did. So the report is written *before* the confirmation
 * run, and then one more audit has to pass with it in place.
 *
 * `status` is a parameter rather than a captured value because the first write happens
 * before the outcome is known.
 */
function writeReport(status, confirmation) {
  const rows = [
    "# Audit streak",
    "",
    `Target: **${target} consecutive clean passes**, plus a confirmation run executed after`,
    `this report exists in the tree. Result: **${status}** — best streak ${best} over`,
    `${attempts.length} attempt(s).`,
    "",
    "Generated by `node scripts/audit-streak.mjs`. A failing attempt resets the streak to zero",
    "rather than being skipped, so the count only ever reflects unbroken clean runs. Each",
    "attempt is a full `node scripts/audit.mjs`: typecheck, the test suite, a production",
    "build and a live server booted on :4321.",
    "",
    "| Attempt | Result | Time | Checks | Streak after |",
    "|---|---|---|---|---|",
  ];
  for (const a of attempts) {
    rows.push(
      `| ${a.attempt} | ${a.clean ? "✅ pass" : "❌ FAIL"} | ${a.seconds}s | ${a.summary} | ${a.streak}/${target} |`,
    );
    for (const failure of a.failures) rows.push(`| | ↳ ${failure.replace(/\|/g, "\\|")} | | | |`);
  }
  if (confirmation) {
    rows.push(
      "",
      `**Confirmation run** — executed after this file was written, so the audit sees its own`,
      `output in the tree: ${confirmation.clean ? "✅ pass" : "❌ FAIL"}, ${confirmation.summary},`,
      `${confirmation.seconds}s.`,
    );
    for (const failure of confirmation.failures) rows.push(`- ${failure}`);
  }
  fs.writeFileSync(path.resolve(root, "AUDIT-STREAK.md"), `${rows.join("\n")}\n`);
}

const runAudit = () => {
  const startedAt = Date.now();
  const run = spawnSync("node", ["scripts/audit.mjs", "--quiet"], {
    cwd: root,
    encoding: "utf-8",
    timeout: 900_000,
  });
  const out = (run.stdout ?? "") + (run.stderr ?? "");
  return {
    clean: run.status === 0,
    seconds: ((Date.now() - startedAt) / 1000).toFixed(1),
    summary: out.match(/(\d+)\/(\d+) checks pass/)?.[0] ?? `exit ${run.status}`,
    failures: [...out.matchAll(/^\s*(\d+)\s+\x1b\[31mFAIL\x1b\[0m\s+(.+)$/gm)].map((m) => `#${m[1]} ${m[2]}`),
  };
};

let confirm = null;
if (streakMet) {
  writeReport("pending");
  confirm = runAudit();
  console.log(
    `confirmation  ${confirm.clean ? "\x1b[32mPASS\x1b[0m" : "\x1b[31mFAIL\x1b[0m"}  ` +
      `${confirm.seconds.padStart(5)}s  ${confirm.summary}  (re-run with this report in the tree)`,
  );
}

const achieved = streakMet && Boolean(confirm?.clean);
writeReport(achieved ? "achieved" : "NOT achieved", confirm);

console.log(
  `\n${achieved ? "\x1b[32m" : "\x1b[31m"}${streak}/${target} consecutive clean passes` +
    `${confirm ? ` + confirmation ${confirm.clean ? "pass" : "FAIL"}` : ""}` +
    ` over ${attempts.length} attempt(s)\x1b[0m — AUDIT-STREAK.md written`,
);
process.exit(achieved ? 0 : 1);
